### PR TITLE
cache containers

### PR DESCRIPTION
**Pull request by angelnu**
### Description

Use cache to avoid timeouts when downloading a container shortly after uploading. It also allows running the CI without providing a github secret to upload a package.

### Related Issue

NA

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Contributing checklist

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** and **LICENSE** document.
- [x] I fully agree to distribute my changes under Apache 2.0 license.

### CODE REVIEW

**Comment by jens-maus** [comment]
Are you sure that this additional caching won't interfere with the actions/cache uses in the build step of the workflow? Because there we use actions/cache already for storing/restoring the buildroot ccache to speed up build tim? Because the maximum size of cache GitHub allows is 5GB per repository AFAIK.

**Comment by angelnu** [comment]
I do not believe they conflict - they should upload to different folders in the cache.

Since the OCI images are ca 150 MBs each then we are talking above 450 MBs max . Do you know if there is a way to check how much of the cache is being used?

I considered just doing a docker save as you proposed but it does not work with multi-arch -> it just captures the current arch. This might not be critical since I had to disable the test on qemu for ARM but it would be later if we want to test on all platforms.

**Comment by jens-maus** [comment]
Ok, I accepted this PR. Let's see how good it will perform and work out. The last nights' snapshot couldn't finish in time btw, because the ccache of the rpi4 build was already overwritten/wiped because of the maximum space allowed for actions/cache use. Perhaps I really have to switch to using own runners instead of using the GitHub runners...

**Comment by angelnu** [comment]
the upload cache should take care of deleting older ones or the CI might be set as ignoring errors.

If problems arise I can redo the test to use a manual save&upload to artifactory.  It is more verbose and would miss the multi-arch but doable.

Own runners will be interesting to add some Homematic HW to them so real tests could be performed so in the long term it would be a good thing to consider. What model would you have in mind: people donating on runners or you buying them (with  eventual donations)?

**Pull request merged**
