### PR TITLE
#1354 Performance Fix within translate.js

### PR DESCRIPTION
**Pull request by theimo1221**
### Description

Performance patch as analyzed in #1354 

### Related Issue
#1354 

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Possible Drawbacks

As this logic in beforehand accidentally scanned whole page, now some containers could be missing if their respectively needed call ist missing.

### Verification Process
Changed file with local override and verified translation on the different pages work as intended

### Release Notes
WebUI performance gain for every page change due to minor change in element selection for translating specific elements.

### Contributing checklist

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** and **LICENSE** document.
- [x] I fully agree to distribute my changes under Apache 2.0 license.

### CODE REVIEW

**Comment by jens-maus** [comment]
Thanks for this PR. However, as the context of this PR fits essentially in the already existing `0111-WebUI-Fix-Translation-Performance` WebUI patch, please rework/add your changes to this already existing WebUI patch instead.

**Comment by theimo1221** [comment]
> Thanks for this PR. However, as the context of this PR fits essentially in the already existing `0111-WebUI-Fix-Translation-Performance` WebUI patch, please rework/add your changes to this already existing WebUI patch instead.

Personally I'd like to keept those seperate, as those address different points/mistakes and that other patch already got included.
But sure, if you want I can  integrate it there.

**Comment by jens-maus** [comment]
Yes, please do so!

**Comment by theimo1221** [comment]
@jens-maus Did as you requested

**Comment by ptweety** [comment]
@theimo1221 may I ask why you have not extended the caching from translateKey over into translatePage? Wouldn't this function benefit even more?

**Comment by theimo1221** [comment]
> @theimo1221 may I ask why you have not extended the caching from translateKey over into translatePage? Wouldn't this function benefit even more?

As far as I remember the translatePage function works quite different in comparision to those translating all elements in a container.

Do you have a page where this translation is too slow, so that I could take a look for optimizations?

**Comment by ptweety** [comment]
No, not really. I was just jumping around the code. But since we are at it, I was playing around with this idea and come up with a hack. But I don't even know if it's worth implementing it.

```
/**
 * Translates a container or full page
 * @param {string} cont The container to translate
 * @param {function} callback The callback function after all translation is done
 */
function setTextContent2(cont, callback) {
  var lang = getLang(),
    container = "#header, #menubar, #content, #footer",
    invisibleBeforeTranslationSelector = ".j_translate";
  container = (cont == undefined) ? container : cont;

  jQuery(container)
    .find("*")
    .addBack()
    .contents()
    .filter(function () {
      // return this.nodeType === 3;
      return this.nodeType === Node.TEXT_NODE && /\S/.test(this.nodeValue);
    })
    .filter(function () {
      if (this.nodeValue.match(/room[A-Z]/) || this.nodeValue.match(/func[A-Z]/)) {
        var result = this.nodeValue.match(/\${\w+}/g);
        if((result == null) && isNoProgramScript(container)) {
          // Remove leading and trailing space and add ${}
          this.nodeValue = "\${"+this.nodeValue.replace(/^\s+|\s+$/g, '')+"}";
        } else {
          // Remove leading and trailing space
          this.nodeValue = this.nodeValue.replace(/^\s+|\s+$/g, '');
        }
      }
      // Only match when contains 'simple string' anywhere in the text
      return this.nodeValue.indexOf('${') != -1;
    })
    .each(function () {
      var jElemParent = jQuery(this).parent(),
      value = jElemParent.html(),
      arrSearchStrings = value.match(/\${\w+}/g);

      // This check is more performant then always processing all Keys.
      if(EscapedLangDict[lang] === undefined) {
        if (Object.keys(HMIdentifier[lang]).length === 0 ||
            Object.keys(langJSON[lang]).length === 0) {
          loadTextResource();
        } else {
          EscapedLangDict[lang] = {};
        }
      }

      jQuery.each(arrSearchStrings, function (index, val) {
        var transKey = val.substring(val.search(/\$\{/) + 2 , val.search(/\}/)).replace(/\<br\/\>|\<br\>/gi,"") // remove possible line breaks
        translatedVal = "";
        //translatedVal = langJSON[lang][transKey];
        //if(translatedVal === undefined) translatedVal = transKey;

        // Check if we already have an escaped variant of the ressource
        if(EscapedLangDict[lang][transKey] !== undefined) {
          translatedVal = EscapedLangDict[lang][transKey];
        }
        else {
          // Get ressource, escape and cach it
          translatedVal = langJSON[lang][transKey];
          if(translatedVal === undefined) translatedVal = transKey;
          translatedVal = unescape(translatedVal);
          EscapedLangDict[lang][transKey] = translatedVal;
        }
        value = value.replace(val, translatedVal);
      });
      if (value != undefined) {
        jElemParent.html(value);
      }

    });

  if (callback) {
    callback();
  }

  jQuery(invisibleBeforeTranslationSelector).show();
}
```

**Pull request merged**
