### PR TITLE
preserve /usr/local in Home Assistant - binding to /data

### PR DESCRIPTION
**Pull request by angelnu**
### Description

Mount /data as /usr/local since Home Assistant does not allow to configure what volumes get mounted

### Related Issue

#1087 

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Contributing checklist

- [ ] My code follows the code style of this project.
- [ ] I have read the **CONTRIBUTING** and **LICENSE** document.
- [ ] I fully agree to distribute my changes under Apache 2.0 license.

### CODE REVIEW

**Comment by jens-maus** [comment]
Thanks. Can you please add a 'oci' platform check around that code in S06InitSystem? And IMHO it also would be good to add a check for the 'RUNNING_IN_HA' env variable you just added to config.json to differentiate between HA and non-HA docker use.

**Comment by jens-maus** [comment]
Thanks for adding the oci check. However, how can be check for the `RUNNING_IN_HA` env variable additional within the docker?

**Comment by angelnu** [comment]
Added but let us check that the environment variable is indeed passed to the script - at least is there when I exec into the container but we cannot test this until we have the new snapshot built.

**Comment by angelnu** [comment]
@jens-maus - this failed due the missing PR fix you already merged to head. Rebasing on latest master

**Comment by angelnu** [comment]
I cherry picked the fix for the deploy test so this PR can be tested overnight

**Pull request merged**
