### PR TITLE
add 0145-WebUI-NaturalSorting

### LINKED ISSUE #1491: Sortierung in der WebUI umstellen auf natürliche Sortierung
**Is your feature request related to a problem? Please describe.**
Die Sortierung in der WebUI basiert auf einfachem Stringvergleich

**Describe the solution you'd like**
Als Verbesserung wurde im Forum die Umstellung auf "natürliche Sortierung" vorgeschlagen

**Describe alternatives you've considered**
...

**Additional context**
Siehe hier: https://homematic-forum.de/forum/viewtopic.php?p=684887#p684887

### PR DESCRIPTION
**Pull request by ptweety**
* change Array.prototype.ex_sortBy
* change iseSortMultiArray

### Description

The existing sorting algorithms have been changed to make use of collators (see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator)

### Related Issue

Fixes #1491 

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Possible Drawbacks

Since this is a change in a very sensible area of the WebUI functionality I would suggest some heavy testing with a variety of different systems and a lot of different devices reached in.

### Verification Process

I tested it in the latest nightly build of Raspberrymatic as well as in my production system.

### Release Notes

The WebUI sorting methods now support natural sorting

### Contributing checklist

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** and **LICENSE** document.
- [x] I fully agree to distribute my changes under Apache 2.0 license.

### CODE REVIEW

**Comment by jens-maus** [comment]
I partly fixed and updated your PR to the latest master branch sources. And I also tried to test it here in my test environment with sorting devices by name in "Status und Bedienung -> Geräte". So can you please elaborate where your improved `webui.js` functions are used. And it would be great if you could show an example screenshot where one can see how the sorting looks before your change and how it looks after your change.

**Comment by ptweety** [comment]
Sure. Please find attached some picture before and after the patch:

unsorted:
unsorted

sorted before patch:
sorted_orig

sorted after patch:
sorted_new

sorted (reverse) after patch:
sorted_new_reverse

**Comment by jens-maus** [comment]
Thx! Now it is clear. And did you do also some benchmarking regarding the performance of the sorting old vs. new? If not, would be great to have some basic benchmarks at hand for comparison.

**Comment by jens-maus** [comment]
Ok, I will merge your PR now so that others can test it tomorrow and report back any potential issues that may come up with it.

**Comment by ptweety** [comment]
Here we go:

Tested with a small timing function in `IseSort()` as follows:

```
IseSort = function(array, colName, reload, popup)
{
  conInfo("Start IseSort");
  console.log(navigator.userAgent);
  console.time("IseSort");
  if (!isSorting)
  {
    ...
  }
  console.timeEnd("IseSort");
};
```

Gives me with:

- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 **Safari/605.1.15** 

| before | after |
| --- | --- |
| [Debug] IseSort: 3.610ms | [Debug] IseSort: 2.173ms |
| [Debug] IseSort: 3.351ms | [Debug] IseSort: 2.981ms |
| [Debug] IseSort: 2.889ms | [Debug] IseSort: 1.938ms |
| [Debug] IseSort: 3.393ms | [Debug] IseSort: 0.694ms |
| [Debug] IseSort: 1.372ms | [Debug] IseSort: 0.734ms |
| [Debug] IseSort: 4.233ms | [Debug] IseSort: 3.737ms |
| [Debug] IseSort: 4.851ms | [Debug] IseSort: 0.758ms |
| [Debug] IseSort: 4.112ms | [Debug] IseSort: 2.918ms |


- Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:93.0) Gecko/20100101 **Firefox/93.0**

| before | after |
| --- | --- |
| IseSort: 4ms - Timer beendet | IseSort: 4ms - Timer beendet |
| IseSort: 4ms - Timer beendet | IseSort: 3ms - Timer beendet |
| IseSort: 2ms - Timer beendet | IseSort: 1ms - Timer beendet |
| IseSort: 5ms - Timer beendet | IseSort: 2ms - Timer beendet |
| IseSort: 2ms - Timer beendet | IseSort: 2ms - Timer beendet |
| IseSort: 3ms - Timer beendet | IseSort: 3ms - Timer beendet |
| IseSort: 4ms - Timer beendet | IseSort: 2ms - Timer beendet |
| IseSort: 3ms - Timer beendet | IseSort: 2ms - Timer beendet |
| IseSort: 2ms - Timer beendet | IseSort: 3ms - Timer beendet |
| IseSort: 2ms - Timer beendet | IseSort: 1ms - Timer beendet |


- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54

| before | after |
| --- | --- |
| IseSort: 3.05029296875 ms | IseSort: 2.2197265625 ms |
| IseSort: 5.875 ms | IseSort: 1.975830078125 ms |
| IseSort: 5.4677734375 ms | IseSort: 1.149169921875 ms |
| IseSort: 5.223876953125 ms | IseSort: 1.376953125 ms |
| IseSort: 8.211181640625 ms | IseSort: 1.654052734375 ms |
| IseSort: 4.800048828125 ms | IseSort: 1.31494140625 ms |
| IseSort: 6.218994140625 ms | IseSort: 1.43212890625 ms |
| IseSort: 3.074951171875 ms | IseSort: 1.739990234375 ms |
| IseSort: 3.89599609375 ms | IseSort: 2.054931640625 ms |


All in all I would say it's faster.

**Comment by mbhomie007** [comment]
Hallo @ptweety @jens-maus 

Snapshot vom 04.11 installiert.

Über "Status und Bedienung -> Geräte" funktioniert die Sortierung/Reihenfolge super!

image

Über "Status und Bedienung -> Gewerke" aber leider **NICHT** so wie gedacht.

image

image

image

image

**Comment by ptweety** [comment]
Die initiale Sortierung wird nicht über JS, sondern per TCL gemacht. Daran habe ich nichts geändert. Wenn du dann aber die Tabelle per Klick auf den Spaltenkopf neu sortierst, dann sollte es korrekt dargestellt werden.

@mbhomie007 : kannst du das bestätigen?

**Comment by ptweety** [comment]
@jens-maus was meinst du? Die Funktion tut zwar korrekt, da aber die initiale Sortierung und Darstellung halt anderswo abläuft, werden die Nutzer evtl. verwirrt. Vielleicht sollte der Patch besser zurückgerollt werden?

**Comment by jens-maus** [comment]
> @jens-maus was meinst du? Die Funktion tut zwar korrekt, da aber die initiale Sortierung und Darstellung halt anderswo abläuft, werden die Nutzer evtl. verwirrt. Vielleicht sollte der Patch besser zurückgerollt werden?

Überblicke das jetzt nicht wirklich. Bitte nochmal zusammenfassen was genau denn jetzt bitte nicht korrekt sortiert wird und was schon. Das einzige was ich verwirrend finde ist, das standardmäßig hier nicht sortiert wird. IMHO sollte man das ändern und z.B. wenn man "Status und Bedienung -> Geräte" betritt sofort die Tabelle nach der neuen Methode sortiert dargestellt werden. Hab ich noch nie verstanden warum es da drei (unsortiert, A-Z, Z-A) statt nur zwei modis (A-Z, Z-A) gibt.

**Comment by ptweety** [comment]
Ich verstehe es selber nicht wirklich, was da krumm ist.

Aber ich sehe, dass die Kanäle in "Status und Bedienung -> Geräte" aus der `control/hdevichannels.htm` generiert werden und eine Neusortierung vorgesehen war:

```
if(firstSort)
{
  Write("//IseSort(arChns,'name',true);");
}
```

Kommentiert man dies aus, so stimmt die Sortierrichtung nicht. Es ist dann Z-A ...

Schreibt man zusätzlich noch folgendes: `Write("iseSetLastSort('name');");` vor die ehemals aaskommentierte Zeile, dann stimmt die Richtung, aber es flackert beim Laden mehrfach. Ist nicht schön ...

```
if(firstSort)
{
  Write("iseSetLastSort('name');");
  Write("IseSort(arChns,'name',true);");
}
```

Analog könnte man das auch in `control/hfuncchannels.htm` mit dem gleichen korrekten und flackerndem Ergebnis machen.

Aber lange Rede kurzer Sinn: die initiale Sortierung unter "Status und Bedienung -> Geräte" ist richtig, unter "Status und Bedienung -> Gewerke" aber nicht.

**Comment by mbhomie007** [comment]
> Aber lange Rede kurzer Sinn: die initiale Sortierung unter "Status und Bedienung -> Geräte" ist richtig, unter "Status und Bedienung -> Gewerke" aber nicht.

Genau!

Unter "Gewerke" muss man jedes Mal, wenn man auf die Seite geht die Sortierung neu im Tabellenkopf anklicken.
Wenn man die Seite wieder verlässt, ist die Einstellung weg.

Unter "Geräte" bleibt die Sortierung richtig erhalten -> funktioniert

**Comment by mbhomie007** [comment]
@ptweety @jens-maus @jp112sdl @Baxxy13 

Habe es nochmal ausprobiert.

Unter "Status und Bedienung -> Gewerke" muss man **2 Mal** auf den Tabellenkopf "Name" klicken um zur üblichen Sortierung (A-Z/0-9) zu kommen.
Verlässt man wie gesagt die Seite, so ist die Einstellung für die Sortierung wieder weg.

Unter "Status und Bedienung -> Geräte" hingegen bleibt die Sortierung richtig erhalten -> funktioniert.
Es wir standartmäßig von (A-Z/0-9) sortiert.

Siehe Screenshots oben.
Ich hoffe ich konnte dies verständlich darstellen.

**Comment by mbhomie007** [comment]
#1508 Ticket separat erstellt

**Pull request merged**
