### PR TITLE
run /bin/SetInterfaceClock every 6 hours

### PR DESCRIPTION
**Pull request by hoedlmoser**
and not every hour.

### CODE REVIEW

**Comment by jens-maus** [comment]
Why every hour? The "*/360" should it actually run every 4 hours AFAIK.

**Comment by hoedlmoser** [comment]
no, looks like `*/x` on minute is "additionally" run every full hour, you can experiment here https://crontab.guru/#*/360_*_*_*_* and click on next. below some logs from a real RM. ;-)

```
# crontab -l | grep '/date'
*/45 * * * *  /bin/date >> /var/log/cron45.log
*/66 * * * *  /bin/date >> /var/log/cron66.log
*/360 * * * *  /bin/date >> /var/log/cron360.log

# tail -4 cron*
==> cron360.log <==
Mon Mar 25 04:00:00 CET 2019
Mon Mar 25 05:00:00 CET 2019
Mon Mar 25 06:00:00 CET 2019
Mon Mar 25 07:00:00 CET 2019

==> cron45.log <==
Mon Mar 25 05:45:00 CET 2019
Mon Mar 25 06:00:00 CET 2019
Mon Mar 25 06:45:00 CET 2019
Mon Mar 25 07:00:00 CET 2019

==> cron66.log <==
Mon Mar 25 04:00:00 CET 2019
Mon Mar 25 05:00:00 CET 2019
Mon Mar 25 06:00:00 CET 2019
Mon Mar 25 07:00:00 CET 2019
# 
```

**Comment by hoedlmoser** [comment]
the _close and comment_ button was just to huge.

**Comment by jens-maus** [comment]
@hoedlmoser Thanks for the hint and tests. So it really seems there is a limit for the minute `*/X` specifier (max: 59). I actually missed that. However, can you please revise your PR so that it will execute every 4 hours and not 6 hours, please. This should be a quite good compromise between getting the interface clock updated regularly and no additional DutyCycle due to a too often execution of `SetInterfaceClock`. Thanks.

**Comment by jens-maus** [comment]
@hoedlmoser Oh, vergiss was ich geschrieben habe :) natürlich habe ich 6h gemeint weil 360/60 ja 6 std sind. sollte nicht zu früh am morgen Tickets mit dem smartphone beantworten :) also alles gut, und danke für den PR.

**Comment by jens-maus** [comment]
@hoedlmoser Mist, du warst zu schnell. bitte wieder zurück auf 6h ;-)

**Comment by hoedlmoser** [comment]
@jens-maus ich glaub jetzt passts. :-)

**Pull request merged**
