### PR TITLE
Fix path for backups and restore in HA

### PR DESCRIPTION
**Pull request by angelnu**
### Description

backup not working due to HA using /data instead of /usr/local

### Related Issue

https://github.com/jens-maus/RaspberryMatic/issues/1128

### Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Contributing checklist

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** and **LICENSE** document.
- [x] I fully agree to distribute my changes under Apache 2.0 license.

### CODE REVIEW

**Comment by jens-maus** [comment]
This looks quite invasive. Why can't we simply move the `/data` bind mount from `S06InitSystem` to a somewhat earlier position? Either we directly move it to `/etc/inittab` or add a new `S00DataMount` or similar. Then all this `/data` vs. `/usr/local` won't be required, I guess.

**Comment by angelnu** [comment]
Not sure if inittab can check busca moving the binary for ha to its own early script is a good and simple idea. Will redo the pr and ping YouTube the.

**Comment by jens-maus** [comment]
Sorry, but I wasn't patient enough and took over the job of integrating your suggested fix myself :)

So here it goes and I do hope it will fix issues for people trying to restore backups in the HA add-on. Thanks for the PR!

**Comment by angelnu** [comment]
no problems - during the week I basically only have one hour for my hobbies so did not start working on it before reading your message.

The one with the upload backup file not working with the HA proxy is harder one to debug...

**Pull request merged**
