### PR TITLE
Security Key can only be set with a working BidCos-RF interface

### PR DESCRIPTION
**Pull request by hicksel**
Expanded the Limitations Section

### CODE REVIEW

**Comment by jens-maus** [comment]
Thanks for the PR. However, I am not sure if adding this is really required. And if so it should IMHO be a general comment that for some functionality working RF Hardware is required (which in fact should be obvious)

**Comment by litti** [comment]
By the way: did someone test that ReGa only accepts the key if needed hardware is present and setting the key lacking needed hardware does not lead to an inconsistent state?

**Comment by hicksel** [comment]
I totally agree with you that there should be a general note of all functionality that is affected by not having an RF Interface. But the reason for bringing this up is that in an Homematic Wired only Setup which I currently have not setting being able to setup a security key also means no password protection for the backup as far as I understand it. In regards to @litti I have tried to set a security key without working RF hardware and have gotten the error notice in the screenshot in issue #203. But apart from that everything seems to still work fine.

**Comment by jens-maus** [comment]
The corresponding line responsible for the error is the following:

https://github.com/eq-3/occu/blob/master/WebUI/www/config/cp_security.cgi#L51

Here the `xmlrpc` command returns an error if no binrpc is listening due to the fact that no RF hardware was found and thus no `rfd` is running. Of course you can add an `if()` around that, but what would happen if rfd is not running, you change the security key via WebUI and later rfd is running, then all devices won't have the correct security key embedded and thus RF communication would not work.

**Comment by hicksel** [comment]
If I understand this correctly then `rfd` is responsible for setting and storing the key for the RF interfaces. One thing that would be interesting to know is if the backup encryption also depends on `rfd` or if this is done separately. Even though I don´t know about the technical details of the `rfd` daemon would it be possible to launch it without any "real" hardware attached, then set the password and stop it again? Or alternatively change the stored key without starting `rfd`.

**Comment by jens-maus** [comment]
There is no backup encryption.

**Pull request closed without merging**
